In [5]:
import numpy as np
import tensorflow as tf


    
def linReg(data_file, target_file):
    
    # W for weights, b for biases, X for inputs, Y_T for 
    W = tf.Variable(tf.zeros([5, 1]), name='Weights')
    b = tf.Variable(0.0, name='Biases')
    X = tf.placeholder(tf.float32, [None, 5], name='Input_X')
    Y_T = tf.placeholder(tf.float32, [None, 1], name='Target_Y')

    
    # Y_P = [X] x [W] + [b]
    Y_P = tf.matmul(X, W) + b
    # MSE = avg((Y_P -Y_T)^2)
    MSE = tf.reduce_mean(tf.reduce_mean(tf.square(Y_P - Y_T), reduction_indices=1, name='Squared_Error'), 
                         name='Mean_Squared_Error')

    # Use Gradient Descent method to minimize MSE
    # Learning rate can be varied
    optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.01)
    train = optimizer.minimize(loss = MSE)
    
    # Load data from files
    inputData = np.load(data_file)
    target = np.load(target_file)    
    trainData = inputData[:,0:70].T
    testData = inputData[:,70:].T
    print(trainData)
    print(testData)

    trainTarget = np.expand_dims(target[0:70], 1)
    testTarget = np.expand_dims(target[70:],1)
    
    # Initialization
    sess = tf.InteractiveSession()
    sess.run(tf.global_variables_initializer())
    initialW = sess.run(W)  
    initialb = sess.run(b)

    # Training model
    wList = []
    for step in range(0,201):
        _, err, currentW, currentb, yhat = sess.run([train, MSE, W, b, Y_P], feed_dict={X: trainData, Y_T: trainTarget})
        wList.append(currentW)
        if not (step % 50) or step < 10:        
            print("Iter: %3d, MSE-train: %4.2f, weights: %s, bias: %.2f"%(step, err, currentW.T, currentb))

    # Testing model
    errTest = sess.run(MSE, feed_dict={X: testData, Y_T: testTarget})
    print("Final testing MSE: %.2f"%(errTest))      

if __name__ == '__main__':
    np.set_printoptions(precision=2)
    linReg('./x.npy', './t.npy')

[[ 5.58  5.46  6.62 -3.42 -1.5 ]
 [-2.95  2.01  9.35  6.37 -0.17]
 [-6.83  5.36  2.25 -5.79  0.51]
 [ 4.26 -1.25 -5.04 -3.28 -4.44]
 [-6.16  2.43 -3.72  2.8   6.9 ]
 [ 9.18  3.18 -9.14  1.93 -9.22]
 [-9.01 -8.6   7.17 -7.66 -6.05]
 [ 8.66 -1.71  5.2   1.02  2.98]
 [ 2.28 -2.41  7.9   3.49  0.08]
 [ 1.73 -8.08 -0.38 -9.83  5.44]
 [ 7.12 -0.03  0.38 -0.94  2.38]
 [ 4.7   2.47 -9.1  -3.69 -8.07]
 [-9.48  4.67 -0.9   2.38 -1.22]
 [-4.64  5.87 -1.59 -5.65  9.68]
 [-5.33 -2.06  0.72 -8.39 -3.8 ]
 [-9.07 -9.16 -7.58 -0.25  0.89]
 [-0.26  3.8   1.6   4.35  3.56]
 [ 6.69  1.88 -2.81  1.36  2.37]
 [-2.4   7.95  8.45  6.07  1.71]
 [-8.84  9.36 -5.21  0.19  2.11]
 [ 4.55  4.23 -0.21  4.97 -8.62]
 [ 5.38  7.39  3.47 -6.46 -5.73]
 [-7.49  8.69 -7.21 -7.93  0.89]
 [-9.36  0.94  0.51 -7.64  2.65]
 [ 8.26  8.95  9.86 -1.85  5.29]
 [ 5.25 -8.67  7.38  5.64  9.21]
 [-9.98  9.46  1.24 -6.8  -8.53]
 [ 5.07 -8.52  3.82 -8.17  6.85]
 [ 2.4   0.95  3.59  6.89 -7.55]
 [ 6.18 -0.08 -1.21 -8.06 -3.01]
 [ 6.99  9